### ISSUE TITLE
add packagequality badge \o/

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/repo-checker#122]
https://packagequality.com/#?package=next-i18next

**Comment by Shuunen** [comment]
dead for now : https://github.com/alexfernandez/package-quality/issues/61

**Comment by alexfernandez** [comment]
Fixed now, server was out of free space. I am planning to move the server to a new provider anyway. Thanks for reporting!

**Comment by Shuunen** [comment]
how cool thx @alexfernandez  😄

**Comment by Shuunen** [comment]
Here is the MD for this repo : 
`[![Package Quality](https://npm.packagequality.com/shield/repo-check.svg)](https://packagequality.com/#?package=repo-check)` 
It renders this nice badge : 
[![Package Quality](https://npm.packagequality.com/shield/repo-check.svg)](https://packagequality.com/#?package=repo-check)

**Comment by Shuunen** [comment]
fixed by caa45d0df9a231f506bdbfcd94e697f042644b7c
